module.exports = {
  title: '差分でわかる エンジニアのゆるい辞典',
  language: 'ja',
  size: 'JIS-B5',
  theme: './style.css',
  entry: [
    'repository.html',                 // 1 Repository (Ch1)
    'clone.html',                      // 2 Clone (Ch1)
    'fork.html',                       // 3 Fork (Ch1)
    'branch.html',                     // 4 Branch (Ch1)
    'commit.html',                     // 5 Commit (Ch1)
    'push.html',                       // 6 Push (Ch1)
    'pull.html',                       // 7 Pull (Ch1)
    'merge.html',                      // 8 Merge (Ch1)
    'rebase.html',                     // 9 Rebase (Ch1)
    'cherry-pick.html',                // 10 Cherry-pick (Ch1)
    'conflict.html',                   // 11 Conflict (Ch1)
    'revert.html',                     // 12 Revert (Ch1)
    'reset.html',                      // 13 Reset (Ch1)
    'tag.html',                        // 14 Tag (Ch1)
    'oss.html',                        // 15 OSS (Ch1)
    'contribute.html',                 // 16 コントリビュート (Ch1)
    'client.html',                     // 21 Client (Ch2)
    'server.html',                     // 22 Server (Ch2)
    'request.html',                    // 23 Request (Ch2)
    'response.html',                   // 24 Response (Ch2)
    'http.html',                       // 25 HTTP (Ch2)
    'https.html',                      // 26 HTTPS (Ch2)
    'dns.html',                        // 27 DNS (Ch2)
    'domain.html',                     // 28 Domain (Ch2)
    'ip-address.html',                 // 29 IP Address (Ch2)
    'port.html',                       // 30 Port (Ch2)
    'cookie.html',                     // 31 Cookie (Ch2)
    'session.html',                    // 32 Session (Ch2)
    'jwt.html',                        // 33 JWT (Ch2)
    'header.html',                     // 34 Header (Ch2)
    'tcp.html',                        // 35 TCP (Ch2)
    'udp.html',                        // 36 UDP (Ch2)
    'tls.html',                        // 37 TLS (Ch2)
    'ssl-certificate.html',            // 38 SSL証明書 (Ch2)
    'lets-encrypt.html',               // 39 Let's Encrypt (Ch2)
    'vpn.html',                        // 40 VPN (Ch2)
    'nat.html',                        // 41 NAT (Ch2)
    'subnet.html',                     // 42 サブネット（Subnet） (Ch2)
    'proxy.html',                      // 43 Proxy（フォワードプロキシ） (Ch2)
    'json.html',                       // 51 JSON (Ch3)
    'yaml.html',                       // 52 YAML (Ch3)
    'toml.html',                       // 53 TOML (Ch3)
    'xml.html',                        // 54 XML (Ch3)
    'csv.html',                        // 55 CSV (Ch3)
    'schema.html',                     // 56 スキーマ（Schema） (Ch3)
    'api.html',                        // 61 API (Ch4)
    'endpoint.html',                   // 62 Endpoint (Ch4)
    'rest.html',                       // 63 REST (Ch4)
    'graphql.html',                    // 64 GraphQL (Ch4)
    'openapi.html',                    // 65 OpenAPI (Ch4)
    'status_code.html',                // 66 Status Code (Ch4)
    'slug.html',                       // 67 slug (Ch4)
    'grpc.html',                       // 71 gRPC (Ch5)
    'websocket.html',                  // 72 WebSocket (Ch5)
    'webhook.html',                    // 73 Webhook (Ch5)
    'pubsub.html',                     // 74 Pub/Sub (Ch5)
    'database.html',                   // 81 Database (Ch6)
    'rdb.html',                        // 82 RDB (Ch6)
    'rdbms.html',                      // 83 RDBMS (Ch6)
    'nosql.html',                      // 84 NoSQL (Ch6)
    'table.html',                      // 85 Table (Ch6)
    'record.html',                     // 86 Record (Ch6)
    'primary-key.html',                // 87 Primary Key (Ch6)
    'foreign-key.html',                // 88 Foreign Key (Ch6)
    'db-index.html',                   // 89 Index (Ch6)
    'sql.html',                        // 90 SQL (Ch6)
    'orm.html',                        // 91 ORM (Ch6)
    'migration.html',                  // 92 Migration (Ch6)
    'seeder.html',                     // 93 Seeder (Ch6)
    'transaction.html',                // 94 Transaction (Ch6)
    'lock.html',                       // 95 Lock (Ch6)
    'row-lock.html',                   // 96 行ロック (Ch6)
    'table-lock.html',                 // 97 テーブルロック (Ch6)
    'deadlock.html',                   // 98 デッドロック (Ch6)
    'n_plus_one.html',                 // 99 N+1 (Ch6)
    'cache.html',                      // 100 Cache (Ch6)
    'normalization.html',              // 101 正規化 (Ch6)
    'denormalization.html',            // 102 非正規化 (Ch6)
    'er_diagram.html',                 // 103 ER図 (Ch6)
    'uuid.html',                       // 104 UUID (Ch6)
    'mysql.html',                      // 105 MySQL (Ch6)
    'postgresql.html',                 // 106 PostgreSQL (Ch6)
    'sqlite.html',                     // 107 SQLite (Ch6)
    'redis.html',                      // 108 Redis (Ch6)
    'mongodb.html',                    // 109 MongoDB (Ch6)
    'view.html',                       // 110 View（ビュー） (Ch6)
    'stored_procedure.html',           // 111 Stored Procedure (Ch6)
    'acid.html',                       // 112 ACID (Ch6)
    'sharding.html',                   // 113 Sharding (Ch6)
    'replication.html',                // 114 レプリケーション (Ch6)
    'connection_pool.html',            // 115 コネクションプール (Ch6)
    'html.html',                       // 121 HTML (Ch7)
    'css.html',                        // 122 CSS (Ch7)
    'javascript.html',                 // 123 JavaScript (Ch7)
    'typescript.html',                 // 124 TypeScript (Ch7)
    'vanilla-js.html',                 // 125 バニラ（Vanilla JS） (Ch7)
    'es-modules.html',                 // 126 ES Modules (Ch7)
    'dom.html',                        // 127 DOM (Ch7)
    'event.html',                      // 128 Event (Ch7)
    'component.html',                  // 129 Component (Ch7)
    'state.html',                      // 130 State (Ch7)
    'props.html',                      // 131 Props (Ch7)
    'csr.html',                        // 132 CSR (Ch7)
    'ssr.html',                        // 133 SSR (Ch7)
    'ssg.html',                        // 134 SSG (Ch7)
    'isr.html',                        // 135 ISR (Ch7)
    'hydration.html',                  // 136 Hydration (Ch7)
    'virtual-dom.html',                // 137 Virtual DOM (Ch7)
    'async.html',                      // 138 非同期（Asynchronous） (Ch7)
    'promise.html',                    // 139 Promise (Ch7)
    'async-await.html',                // 140 async・await (Ch7)
    'css-framework.html',              // 141 CSSフレームワーク (Ch7)
    'ui-component-library.html',       // 142 UIコンポーネントライブラリ (Ch7)
    'nodejs.html',                     // 143 Node.js (Ch7)
    'bun.html',                        // 144 Bun (Ch7)
    'deno.html',                       // 145 Deno (Ch7)
    'react.html',                      // 146 React (Ch7)
    'vue.html',                        // 147 Vue (Ch7)
    'nextjs.html',                     // 148 Next.js (Ch7)
    'nuxtjs.html',                     // 149 Nuxt.js (Ch7)
    'vite.html',                       // 150 Vite (Ch7)
    'eslint.html',                     // 151 ESLint (Ch7)
    'biome.html',                      // 152 Biome (Ch7)
    'oxc.html',                        // 153 OXC (Ch7)
    'tailwindcss.html',                // 154 Tailwind CSS (Ch7)
    'mui.html',                        // 155 MUI (Ch7)
    'shadcn-ui.html',                  // 156 shadcn/ui (Ch7)
    'electron.html',                   // 157 Electron (Ch7)
    'pwa.html',                        // 158 PWA (Ch7)
    'webassembly.html',                // 159 WebAssembly (Ch7)
    'a11y.html',                       // 160 a11y（アクセシビリティ） (Ch7)
    'i18n.html',                       // 161 i18n（国際化） (Ch7)
    'core-web-vitals.html',            // 162 Core Web Vitals (Ch7)
    'redux.html',                      // 163 Redux (Ch7)
    'zustand.html',                    // 164 Zustand (Ch7)
    'pinia.html',                      // 165 Pinia (Ch7)
    'ruby.html',                       // 171 Ruby (Ch8)
    'python.html',                     // 172 Python (Ch8)
    'go.html',                         // 173 Go (Ch8)
    'php.html',                        // 174 PHP (Ch8)
    'java.html',                       // 175 Java (Ch8)
    'rust.html',                       // 176 Rust (Ch8)
    'rails.html',                      // 177 Rails (Ch8)
    'express.html',                    // 178 Express (Ch8)
    'hono.html',                       // 179 Hono (Ch8)
    'django.html',                     // 180 Django (Ch8)
    'fastapi.html',                    // 181 FastAPI (Ch8)
    'flask.html',                      // 182 Flask (Ch8)
    'gin.html',                        // 183 Gin (Ch8)
    'laravel.html',                    // 184 Laravel (Ch8)
    'spring-boot.html',                // 185 Spring Boot (Ch8)
    'index.html',                      // 301 Docker (Ch13)
    '019-image.html',                  // 305 Image (Ch13)
    '021-container.html',              // 309 Container (Ch13)
    '065-volume.html',                 // 313 Volume (Ch13)
    '042-compose.html',                // 321 Docker Compose (Ch13)
    '015-vm.html',                     // 401 VM (Ch16)
    '089-kubernetes.html',             // 441 Kubernetes (Ch16)
    '014-devops.html',                 // 701 DevOps (Ch14)
  ],
  output: ['book.pdf'],
};